<h5>
<i>Site Guide:</i><br>
<a href="http://cruisenews.net/control/display/shipsatsea.php">Ships at Sea</a><br>
<a href="http://cruisenews.net/control/display/voyagelogs.php">Voyage Logs</a><br>
<a href="http://cruisenews.net/control/display/discoveries.php">New Discoveries</a><br>
<a href="http://cruisenews.net/control/display/boattypes.php">Affordable Cruising Sailboats</a><br>
<a href="http://cruisenews.net/control/display/books.php">Recommended Books</a><br>
<hr><h5>
<a href="http://cruisenews.net/control/display/pagetemplate.php?cat_id=52">Charts and Imagery</a><br>
<a href="http://cruisenews.net/control/display/pagetemplate.php?cat_id=49">Navigation</a><br>
<a href="http://cruisenews.net/control/display/pagetemplate.php?cat_id=48">Weather and Tide</a><br>
<a href="http://cruisenews.net/control/display/pagetemplate.php?cat_id=50">Piloting Skills</a><br>
<a href="http://cruisenews.net/control/display/pagetemplate.php?cat_id=51">Instruments and Software</a><br>
<hr><h5>
<a href="http://cruisenews.net/control/display/pagetemplate.php?cat_id=9">Motors</a><br>
<a href="http://cruisenews.net/control/display/pagetemplate.php?cat_id=10">Sails</a><br>
<a href="http://cruisenews.net/control/display/pagetemplate.php?cat_id=17">Anchoring</a><br>
<a href="http://cruisenews.net/control/display/pagetemplate.php?cat_id=11">Lines, Rigging</a><br>
<a href="http://cruisenews.net/control/display/pagetemplate.php?cat_id=14">Oars</a><br>
<a href="http://cruisenews.net/control/display/pagetemplate.php?cat_id=18">Steering</a><br>
<hr><h5>
<a href="http://cruisenews.net/control/display/pagetemplate.php?cat_id=8">Stoves and Heaters</a><br>
<a href="http://cruisenews.net/control/display/pagetemplate.php?cat_id=16">Heads</a><br>
<a href="http://cruisenews.net/control/display/pagetemplate.php?cat_id=54">Refrigeration</a><br>
<a href="http://cruisenews.net/control/display/pagetemplate.php?cat_id=95">Water</a><br>
<a href="http://cruisenews.net/control/display/pagetemplate.php?cat_id=12">Dinghies and Liferafts</a><br>
<a href="http://cruisenews.net/control/display/pagetemplate.php?cat_id=15">Diving Equipment</a><br>
<a href="http://cruisenews.net/control/display/pagetemplate.php?cat_id=13">Miscellaneous Equipment</a><br>
<hr><h5>
<a href="http://cruisenews.net/control/display/pagetemplate.php?cat_id=2">Light and Power</a><br>
<a href="http://cruisenews.net/control/display/pagetemplate.php?cat_id=3">Batteries</a><br>
<a href="http://cruisenews.net/control/display/pagetemplate.php?cat_id=4">Solar Power</a><br>
<a href="http://cruisenews.net/control/display/pagetemplate.php?cat_id=5">LED Lighting</a><br>
<a href="http://cruisenews.net/control/display/pagetemplate.php?cat_id=6">Wind Generators</a><br>
<a href="http://cruisenews.net/control/display/pagetemplate.php?cat_id=7">Non-Electric Light</a><br>
<a href="http://cruisenews.net/control/display/pagetemplate.php?cat_id=57">Generators</a><br>
<hr><h5>
<a href="http://cruisenews.net/control/display/pagetemplate.php?cat_id=19">Amateur Radio</a><br>
<a href="http://cruisenews.net/ham/hamtest.html">Ham License Help</a><br>
<a href="http://cruisenews.net/control/display/pagetemplate.php?cat_id=20">Marine Nets</a><br>
<a href="http://cruisenews.net/control/display/hamradioemail.php">Ham Radio Email</a><br>
<hr><h5>
<a href="http://cruisenews.net/control/display/pagetemplate.php?cat_id=89">Cruising Advice</a><br>
<a href="http://cruisenews.net/control/display/pagetemplate.php?cat_id=92">Health Information</a><br>
<a href="http://cruisenews.net/control/display/pagetemplate.php?cat_id=94">Provisioning</a><br>
<a href="http://cruisenews.net/control/display/pagetemplate.php?cat_id=93">Safety</a><br>
<hr><h5>
<a href="http://cruisenews.net/control/display/pagetemplate.php?cat_id=36">Sailor's Homepages</a><br>
<a href="http://cruisenews.net/control/display/pagetemplate.php?cat_id=37">Boating Magazines</a><br>
<a href="http://cruisenews.net/control/display/pagetemplate.php?cat_id=38">Cruising Guides</a><br>
<a href="http://cruisenews.net/control/display/cruising_regions.php">Cruising Regions</a><br>
<a href="http://cruisenews.net/control/display/pagetemplate.php?cat_id=40">Radical Concepts</a><br>
<a href="http://cruisenews.net/control/display/pagetemplate.php?cat_id=41">Sailing Link Sites</a><br>
<a href="http://cruisenews.net/control/display/pagetemplate.php?cat_id=42">Sailing Forums</a><br>
<a href="http://cruisenews.net/control/display/pagetemplate.php?cat_id=56">News Articles</a><br>
<a href="http://cruisenews.net/control/display/pagetemplate.php?cat_id=91">Organizations</a><br>
<a href="http://cruisenews.net/control/display/pagetemplate.php?cat_id=90">Nautical Supplies</a><br>
<a href="http://cruisenews.net/control/display/pagetemplate.php?cat_id=39">Miscellaneous Resources</a><br>
<hr><h5>
<a href="http://cruisenews.net/control/display/pagetemplate.php?cat_id=22">Boat Designs</a><br>
<a href="http://cruisenews.net/control/display/pagetemplate.php?cat_id=23">Boatbuilding Stories</a><br>
<a href="http://cruisenews.net/control/display/pagetemplate.php?cat_id=24">Boatbuilding Materials</a><br>
<a href="http://cruisenews.net/control/display/pagetemplate.php?cat_id=25">Boatbuilding Tools</a><br>
<a href="http://cruisenews.net/control/display/pagetemplate.php?cat_id=26">Boatbuilding Methods</a><br>
<a href="http://cruisenews.net/control/display/pagetemplate.php?cat_id=27">Boatbuilding Repairs</a><br>
<a href="http://cruisenews.net/control/display/pagetemplate.php?cat_id=28">Boatbuilding Restoration</a><br>
<a href="http://cruisenews.net/control/display/pagetemplate.php?cat_id=29">Boatbuilding Designers</a><br>
</h5>
