<tr>
<td><h3><hr><i>MAIN PAGES:</i></h3>
</td>
</tr>
<tr>
<td>
<h3><a href="shipsatsea.php">Ships at Sea</a></h3>
</td>
</tr>
<tr>
<td><h3><a href="voyagelogs.php">Voyage Logs</a></h3>
</td>
</tr>
<tr>
<td><h3><a href="discoveries.php">New Discoveries</a></h3>
</td>
</tr>
<tr>
<td><h3><a href="books.php">Sailing Books</a></h3>
</td>
</tr>
<tr>
<td><h3><a href="boattypes.php">Offshore and Coastal Cruising Sailboats</a></h3>
</td>
</tr>
<tr>
<td><h3><hr><i>FORUMS:</i></h3>
</td>
</tr>
<tr>
<td><h3><a href="http://www.cruisenews.net/forum/index.php">Cruising Sailor Forum</a><br>
<a href="http://www.cruisenews.net/forum/viewforum.php?f=45">Maritime Mobile Ham Forum</a><br>
<a href="http://www.cruisenews.net/forum/viewforum.php?f=62">Windvane Forum</a><br>
<a href="http://www.cruisenews.net/forum/viewforum.php?f=5">Cruising Sailboats For Sale</a><br>
<a href="http://www.cruisenews.net/forum/viewforum.php?f=13">Crew Positions</a><br>
<a href="http://www.cruisenews.net/forum/viewforum.php?f=5">Cruising Sailboats For Sale</a><br>
<a href="http://www.cruisenews.net/forum/viewforum.php?f=14">Delivery Services Directory</a>
</h3>
</td>
</tr>
<td><hr><p>
<p align=left><b>
The Guide to Sailing and Cruising Stories is a collection of personal
accounts by sail and motor boat cruisers.  This site is dedicated to bringing you the best stories on sailing and
cruising available on the internet.&nbsp;

<p align=left><b>
The Guide to Sailing and Cruising Stories focuses on personal accounts
of bluewater ocean sailing voyages, coastal cruising, ocean passagemaking,
exploring the wilderness by boat, living aboard, river voyages and adventure
travel by boat around the world.  The stories include a wealth of information on destinations, equipment,
remarkable situations and general foolery for anyone interested in traveling
in their own yacht or boat.
<a href="windvane.html"><img src="myimage.jpg" border="0"></a>
<a href="http://cruisenews.net/brewing/"><img src="myimage.jpg" border="0"></a>
<a href="install_java_on_redhat_9.html"><img src="myimage.jpg" border="0"></a>
<p align=left><b>
First hand cruising adventure accounts taken directly from the sailors'
own personal pages make for the best information on sailing and cruising.
<p><b>
Send mail to
<a href="mailto:admin@cruisenews.net">admin@cruisenews.net</a>
&nbsp;Suggestions, comments and new links are welcome and appreciated!
<p><b>
Copyright 1998 - 2007 Cruisenews Network
