<script type="text/javascript"><!--
google_ad_client = "pub-0460282711081659";
google_ad_width = 728;
google_ad_height = 90;
google_ad_format = "728x90_as";
google_color_border = ["FFFFFF","E0FFE3","DFF2FD","FDFFCA"];
google_color_bg = ["FFFFFF","E0FFE3","DFF2FD","FDFFCA"];
google_color_link = ["0000FF","0000CC","0000CC","0000CC"];
google_color_url = ["0000FF","008000","008000","008000"];
google_color_text = "000000";
//--></script>
<script type="text/javascript"